server:
  port: 8080

spring:
  application:
    name: identity-service


---
spring:
  config:
    activate:
      on-profile: dev
  mongodb:
    uri: ${MONGO_URI}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: prod
  mongodb:
    uri: ${MONGO_URI}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
